name: "Deployment"

on:
  push: # Auto trigger
    tags:
      - v*
  workflow_dispatch: # Manual trigger
    inputs:
      deployBranch:
        required: true
        description: "Select branch to deploy"
        default: "master"
        type: choice
        options:
          - master

env:
  DOCKER_BUILDKIT: 1
  feishu_robot_webhook: https://open.feishu.cn/open-apis/bot/v2/hook/887c0f7f-7fbb-43b1-840b-46c5f86faa97
  registry_domain: ghcr.io
  registry_name: listen2u/listen2u-services

run-name: Deploy ${{ github.ref_name }} to production by @${{ github.actor }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Start deployment notification
        run: |
          FEISHU_MESSAGE=$(cat <<EOF
          {
            "msg_type": "text",
            "content": {
              "text": "开始部署 ${{ github.ref_name }} 到生产环境，操作人: ${{ github.actor }}"
            }
          }
          EOF
          )
          curl -X POST -H "Content-Type: application/json" -d "$FEISHU_MESSAGE" ${{ env.feishu_robot_webhook }}

      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.registry_domain }}
          username: ${{ secrets.GITHUB_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            RAILS_ENV=production
          push: true
          tags: ${{ env.registry_domain }}/${{ env.registry_name }}:${{ github.ref_name }}, ${{ env.registry_domain }}/${{ env.registry_name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: ${{ vars.DOKKU_PRODUCTION_GIT_URL }}
          ssh_private_key: ${{ secrets.DOKKU_DEPLOY_KEY }}
          deploy_docker_image: ${{ env.registry_domain }}/${{ env.registry_name }}:${{ github.ref_name }}

      - name: Deployment complete notification
        run: |
          FEISHU_MESSAGE=$(cat <<EOF
          {
            "msg_type": "text",
            "content": {
              "text": "部署 ${{ github.ref_name }} 完成，操作人: ${{ github.actor }}"
            }
          }
          EOF
          )
          curl -X POST -H "Content-Type: application/json" -d "$FEISHU_MESSAGE" ${{ env.feishu_robot_webhook }}
